#ifndef MONTHLY_LAYOUT
#define MONTHLY_LAYOUT

#define DOW_WIDTH 86
#define DOW_HEIGHT 64
#define DOW_COLUMNS 7
#define DOW_ROWS 6

#define DOW_GRID_HEADER_HEIGHT DOW_HEIGHT/2

#define DOW_GRID_Y_OFFSET EPD_7IN3F_HEIGHT-DOW_HEIGHT*DOW_ROWS
#define DOW_GRID_WIDTH DOW_WIDTH*DOW_COLUMNS
#endif