#ifndef MONTHLY_LAYOUT
#define MONTHLY_LAYOUT

#define DOW_WIDTH 86
#define DOW_HEIGHT 65
#define DOW_COLUMNS 7
#define DOW_ROWS 6

#define DOW_GRID_Y_OFFSET EPD_7IN3F_HEIGHT-DOW_HEIGHT*DOW_ROWS
#endif